name: My Test
on:
  push:
    branches:
    - main

jobs:
  the_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Write a step summary
        run: |
          # Get a JSON array of failed unit tests
          FAILED_UNIT_TESTS=$(jq 'to_entries | map(.value | select(.status == 1))' unit_tests.json)

          FAIL_COUNT=$(echo $FAILED_UNIT_TESTS | jq 'length')

          echo "# Test failures" >> $GITHUB_STEP_SUMMARY
          echo "$FAIL_COUNT test failures." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          for i in $( seq $FAIL_COUNT ); do
            CURRENT_FAIL=$(echo $FAILED_UNIT_TESTS | jq --arg i $i '.[($i | tonumber) - 1]')
            TEST=$(echo $CURRENT_FAIL | jq '.name')
            MESSAGE=$(echo $CURRENT_FAIL | jq '.message')

            echo "### $TEST" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo $MESSAGE >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          done

