name: My Test
on:
  push:
    branches:
    - main

jobs:
  the_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Write a step summary
        run: |
          # Get a JSON array of failed unit tests
          jq 'to_entries | map(.value | select(.status == 1))' unit_tests.json > ./failed_unit_tests.json

          FAIL_COUNT=$(jq -r 'length' ./failed_unit_tests.json)

          echo "# Test failures" >> $GITHUB_STEP_SUMMARY
          echo "$FAIL_COUNT test failures." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          for i in $( seq $FAIL_COUNT ); do
            CURRENT_FAIL=$(jq -r --arg i $i '.[($i | tonumber) - 1]' ./failed_unit_tests.json)
            TEST=$(jq -r '.name' <$CURRENT_FAIL)
            MESSAGE=$(jq -r '.message' <$CURRENT_FAIL)

            echo "### `$TEST`" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo $MESSAGE >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          done

