name: Test Add BYOND to path

on:
  workflow_dispatch:

jobs:
  add_byond_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download BYOND releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download byond_515.1642 --pattern byond_linux.zip --dir ~
      - name: Unzip and make BYOND
        run: |
          cd ~
          unzip byond_linux.zip
          cd byond
          make here
      - name: Add BYOND environmental variables
        run: |
          source ~/byond/bin/byondsetup
          echo "$PATH" >> $GITHUB_PATH
          # Apply any environment variables from byond setup
          printenv > $GITHUB_ENV
      - name: Print env
        run: printenv
      - name: Test using BYOND
        run: |
          DreamDaemon -help
