name: Test Add BYOND to path

on:
  workflow_dispatch:

jobs:
  add_byond_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download BYOND releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo likelakers2/byond-versions byond_515.1642 --pattern byond_linux.zip --dir ~
      - name: Unzip and make BYOND
        run: |
          cd ~
          unzip byond_linux.zip
          echo "$HOME/byond/bin" >> $GITHUB_PATH
          chmod --recursive $HOME/byond/bin +x
      - name: Test using BYOND
        run: |
          DreamDaemon -help
