name: Test Add BYOND to path

on:
  workflow_dispatch:

jobs:
  add_byond_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download BYOND releases
        run: |
          curl --fail "https://github.com/LikeLakers2/github_actions_test/releases/download/byond_515.1642/byond_linux.zip"
      - name: Add BYOND to path
        run: |
          OLD_PWD=$PWD
          unzip byond_linux.zip -d ~
          cd ~/byond
          make here
          echo "$PWD/bin" >> $GITHUB_PATH
          cd $OLD_PWD
      - name: Test using BYOND
        run: |
          DreamDaemon -help
