name: Test Add BYOND to path

on:
  workflow_dispatch:
    inputs:
      major:
        description: The major version of BYOND to add (the part before the `.`)
        required: true
        type: number
      minor:
        description: The minor version of BYOND to add (the part after the `.`)
        required: true
        type: number

permissions:
  contents: write

env:
  BYOND_MAJOR: ${{inputs.major}}
  BYOND_MINOR: ${{inputs.minor}}
  NEW_RELEASE_TITLE: "BYOND ${{inputs.major}}.${{inputs.minor}}"
  NEW_TAG_NAME: "byond_${{inputs.major}}.${{inputs.minor}}"

jobs:
  add_byond_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download BYOND releases
        run: |
          curl --fail "https://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" --output byond_linux.zip
      - name: Add BYOND to path
        run: |
          OLD_PWD=$PWD
          unzip byond_linux.zip -d ~
          cd ~/byond
          make here
          echo "source $PWD/bin/byondsetup" >> ~/.bash_profile
          cd $OLD_PWD
      - name: Test using BYOND
        run: |
          DreamDaemon -help
