name: Test Add BYOND to path

on:
  workflow_dispatch:

jobs:
  add_byond_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download BYOND releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download byond_515.1642 --pattern byond_linux.zip --dir ~
      - name: Add BYOND to path
        run: |
          OLD_PWD=$PWD
          cd ~
          unzip byond_linux.zip
          cd byond
          make here
          echo "$PWD/bin" >> $GITHUB_PATH
          cd $OLD_PWD
      - name: Test using BYOND
        run: |
          DreamDaemon -help
